# Generated by Django 5.2 on 2025-05-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0002_alter_offers_options_offers_create_date_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="offers",
            table="offers_offers",
        ),
    ]
