# Generated by Django 5.2 on 2025-05-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="passwordHash",
            new_name="password_hash",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="profileImage",
            new_name="profile_image",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="userId",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="userName",
            new_name="user_name",
        ),
    ]
