# Generated by Django 5.2 on 2025-05-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_rename_name_user_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="password_hash",
            new_name="password",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_name",
            new_name="username",
        ),
    ]
