# Generated by Django 5.2 on 2025-05-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_rename_password_hash_user_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
