# Generated by Django 5.2 on 2025-05-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0005_user_is_active_user_is_staff_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
