# Generated by Django 5.2 on 2025-05-06 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("propertyId", models.IntegerField()),
                ("PropertyAddress", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("postalCode", models.IntegerField()),
                ("propertyPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("propertyType", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("roomCount", models.IntegerField()),
                ("bedroomCount", models.IntegerField()),
                ("bathroomCount", models.IntegerField()),
                ("isSold", models.BooleanField()),
                ("listingDate", models.DateField()),
                ("squareMeters", models.IntegerField()),
                (
                    "propertyValuation",
                    models.DecimalField(decimal_places=2, max_digits=100),
                ),
                ("sellerId", models.IntegerField()),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="property.property",
                    ),
                ),
            ],
        ),
    ]
