# Generated by Django 5.2 on 2025-05-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="PropertyAddress",
            new_name="Property_address",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="bathroomCount",
            new_name="bathroomcount",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="bedroomCount",
            new_name="bedroomcount",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="isSold",
            new_name="is_sold",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="listingDate",
            new_name="listing_date",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="postalCode",
            new_name="postalcode",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="propertyId",
            new_name="property_id",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="propertyPrice",
            new_name="property_price",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="propertyType",
            new_name="property_type",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="propertyValuation",
            new_name="property_valuation",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="roomCount",
            new_name="roomcount",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="sellerId",
            new_name="seller_id",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="squareMeters",
            new_name="squaremeters",
        ),
    ]
