# Generated by Django 5.2 on 2025-05-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_rename_propertyaddress_property_property_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="Property_address",
            new_name="property_address",
        ),
    ]
