# Generated by Django 5.2 on 2025-05-07 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_rename_name_user_name_and_more"),
        ("property", "0003_rename_property_address_property_property_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="image",
            new_name="image_cover",
        ),
        migrations.AlterField(
            model_name="property",
            name="seller_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="User.user"
            ),
        ),
    ]
