# Generated by Django 5.2 on 2025-05-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_rename_image_property_image_cover_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="image_cover",
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_price",
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
