# Generated by Django 5.2 on 2025-05-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0005_alter_property_image_cover_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.CharField(max_length=4096),
        ),
    ]
