# Generated by Django 5.2 on 2025-05-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_cover',
            field=models.ImageField(upload_to='property_images/'),
        ),
    ]
