# Generated by Django 5.2.1 on 2025-05-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0007_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_address",
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(max_length=4096),
        ),
    ]
